import type { Metadata } from 'next'
import { Fraunces, Barlow } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Header from '@/components/header/Header'

const fraunces = Fraunces({ subsets: ['latin'] })
const barlow = Barlow({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-barlow',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(barlow.className, 'bg-lightCream')}>
        <Header />
        {children}
      </body>
    </html>
  )
}
